name: Release

"on":
  workflow_dispatch: {}

# We will add automatic release stuff here as soon as possible

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - run: mvn -B dependency:go-offline -q
      - run: mvn -B verify
        if: github.ref != 'refs/heads/master'
      - uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: surefire
          path: '*/target/surefire-reports/*.xml'
          reporter: java-junit
          list-suites: failed
          list-tests: failed
          fail-on-error: false
